### ISSUE TITLE
TusClientProvider not working on React 18

### ISSUE THREAD

**Issue by kallebysantos** [kqito/use-tus#32]
Since React 18 was removed `children` property from `React.FC` the TusClientProvider is not working.
<img width="914" alt="image" src="https://user-images.githubusercontent.com/105971119/169664258-88201f10-6647-4348-ad93-3542d60aa2f2.png">

**Comment by kqito** [comment]
This bug has been fixed on [v0.6.1](https://www.npmjs.com/package/use-tus/v/0.6.1) by your contribution !!

Thank you !!
