### ISSUE TITLE
Request for termination support

### ISSUE THREAD

**Issue by dkmorgan** [kqito/use-tus#51]
Would it be possible to support the `shouldTerminate` argument in `abort()`? (Reference: [tus-js-client](https://github.com/tus/tus-js-client/blob/main/lib/upload.js#L450))
I cannot currently terminate the upload and delete the resource on the server.

**Comment by kqito** [comment]
Thank you for your request! It seems like there is a bug in use-tus due to the failure to pass the shouldTerminate argument to the abort function.

I'll address this problem shortly.

**Comment by kqito** [comment]
This issue has been fixed in version [v0.8.2](https://github.com/kqito/use-tus/releases/tag/v0.8.2). Could you please try using the new release?

**Comment by dkmorgan** [comment]
@kqito

I tried out [v0.8.2](https://github.com/kqito/use-tus/releases/tag/v0.8.2).
`abort(true)` now aborts the upload in progress and is followed by a DELETE request to terminate the upload.

Thank you so much for such a prompt fix!
